In [1]:
import numpy as np

post1 = np.array([100, 120, 150, 180, 200, 220, 250])
post2 = np.array([80, 90, 110, 130, 160, 180, 210])
post3 = np.array([150, 170, 190, 210, 230, 260, 300])

weekly_likes = np.vstack((post1, post2, post3))

print(weekly_likes)

[[100 120 150 180 200 220 250]
 [ 80  90 110 130 160 180 210]
 [150 170 190 210 230 260 300]]
