In [1]:
import numpy as np

chat = np.array([
    [10, 15, 12, 8, 20, 18, 14],
    [5,  7,  3,  6,  4,  8,  2],
    [12, 10, 15, 20, 18, 14, 16]
])

print("Original Chat Data:", chat)


new_user = np.array([8, 12, 10, 15, 9, 11, 13])

chat = np.insert(chat, 3, new_user, axis=0)

print("After Adding New User:", chat)

total_messages = np.sum(chat, axis=1)
least_user = np.argmin(total_messages)

chat = np.delete(chat, least_user, axis=0)

print("After Removing User with Least Messages:", chat)


Original Chat Data: [[10 15 12  8 20 18 14]
 [ 5  7  3  6  4  8  2]
 [12 10 15 20 18 14 16]]
After Adding New User: [[10 15 12  8 20 18 14]
 [ 5  7  3  6  4  8  2]
 [12 10 15 20 18 14 16]
 [ 8 12 10 15  9 11 13]]
After Removing User with Least Messages: [[10 15 12  8 20 18 14]
 [12 10 15 20 18 14 16]
 [ 8 12 10 15  9 11 13]]
