In [1]:
import numpy as np

playlist = np.array([
    [10, 5, 8],
    [7, 12, 6],
    [15, 4, 9]
])

print("Original Playlist Grid:", playlist)

transpose_T = playlist.T
print("Transpose using T:", transpose_T)

transpose_func = np.transpose(playlist)
print("Transpose using np.transpose():", transpose_func)

Original Playlist Grid: [[10  5  8]
 [ 7 12  6]
 [15  4  9]]
Transpose using T: [[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]
Transpose using np.transpose(): [[10  7 15]
 [ 5 12  4]
 [ 8  6  9]]
