In [1]:
import numpy as np

prices = np.array([250, 300, 150, 400, 350, 200, 450, 500, 100, 600, 700, 800])

price_2D = prices.reshape(3, 4)
print("2D array of prices:", price_2D)

ravel_array = price_2D.ravel()
print("Raveled array:", ravel_array)

flatten_array = price_2D.flatten()
print("Flattened array:", flatten_array)

resized_array = np.resize(price_2D, (4, 3))
print("Resized array:", resized_array)

2D array of prices: [[250 300 150 400]
 [350 200 450 500]
 [100 600 700 800]]
Raveled array: [250 300 150 400 350 200 450 500 100 600 700 800]
Flattened array: [250 300 150 400 350 200 450 500 100 600 700 800]
Resized array: [[250 300 150]
 [400 350 200]
 [450 500 100]
 [600 700 800]]
